export class Content {
  subTitle: string
  imageUrl: string
  videoUrl: string
  fileUrl: string
  linkUrl: string
  summary: string
  author: string
  source: string
  isRecommend: boolean
  isHot: boolean
  isColor: boolean
  content: string
  id: number
  nodeId: number
  publishmentSystemId: number
  addUserName: string
  lastEditUserName: string
  writingUserName: string
  lastEditDate: Date
  taxis: number
  contentGroupNameCollection: string
  tags: string
  sourceId: number
  referenceId: number
  isChecked: boolean
  checkedLevel: number
  comments: number
  photos: number
  hits: number
  hitsByDay: number
  hitsByWeek: number
  hitsByMonth: number
  lastHitsDate: Date
  title: string
  isTop: string
  addDate: Date
}
