export class ContentAttributeName {
    public static SubTitle: string = "subTitle"
    public static ImageUrl: string = "imageUrl"
    public static VideoUrl: string = "videoUrl"
    public static FileUrl: string = "fileUrl"
    public static LinkUrl: string = "linkUrl"
    public static Summary: string = "summary"
    public static Author: string = "author"
    public static Source: string = "source"
    public static IsRecommend: string = "isRecommend"
    public static IsHot: string = "isHot"
    public static IsColor: string = "isColor"
    public static Content: string = "content"
    public static Id: string = "id"
    public static NodeId: string = "nodeId"
    public static PublishmentSystemId: string = "publishmentSystemId"
    public static AddUserName: string = "addUserName"
    public static LastEditUserName: string = "lastEditUserName"
    public static WritingUserName: string = "writingUserName"
    public static LastEditDate: string = "lastEditDate"
    public static Taxis: string = "taxis"
    public static ContentGroupNameCollection: string = "contentGroupNameCollection"
    public static Tags: string = "tags"
    public static SourceId: string = "sourceId"
    public static ReferenceId: string = "referenceId"
    public static IsChecked: string = "isChecked"
    public static CheckedLevel: string = "checkedLevel"
    public static Comments: string = "comments"
    public static Photos: string = "photos"
    public static Hits: string = "hits"
    public static HitsByDay: string = "hitsByDay"
    public static HitsByWeek: string = "hitsByWeek"
    public static HitsByMonth: string = "hitsByMonth"
    public static LastHitsDate: string = "lastHitsDate"
    public static Title: string = "title"
    public static IsTop: string = "isTop"
    public static AddDate: string = "addDate"

    public static getExtendAttributeName(attributeName: string): string {
        return attributeName + "_Extend"
    }
}

export class InputType {
    public static TextEditor: string = "TextEditor"
    public static TextArea: string = "TextArea"
    public static Text: string = "Text"
    public static DateTime: string = "DateTime"
    public static Image: string = "Image"
}