# configuration for "master" branch
-
  branches:
    only:
      - master

  version: 6.1.{build}

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gitbook-cli -g
    - npm install gulp -g
    - npm install

  build: script

  skip_tags: true

  cache:
    - node_modules                        # local npm modules

  build_script:
    - gulp build

# configuration for "dev" branch
-
  branches:
    only:
      - dev

  version: 6.1.{build}

  environment:
    nodejs_version: "8"
    TreatWarningsAsErrors: false

  install:
    - npm install gulp-cli -g
    - npm install gitbook-cli -g
    - npm install

  skip_tags: true

  cache:
    - node_modules                        # local npm modules

  before_build:
    - gitbook install getting-started

  after_build:
    - gulp build